### ISSUE TITLE
Analyzing Salesforce Data with Looker - IE11 Deploy to Bluemix Produces 404 Not Found Error

### ISSUE THREAD

**Issue by kgiffels** [ibm-cds-labs/pipes#20] opened 2015-08-05 15:10 UTC
Analyzing Salesforce Data with Looker 
Win7, IE11
https://developer.ibm.com/clouddataservices/simple-data-pipe/

1. click on the tutorial link, https://developer.ibm.com/clouddataservices/simple-data-pipe/
2. click on the Deploy to Bluemix button, 404! Good grief!  We couldn’t find anything here! Maybe try the search?
3. works correctly on FF ESR 38.1

**Comment by ptitzler** [comment] 2015-10-23 00:01
We have been deploying the Simple Data Pipes application for the past 3 month (using IE, FF and Chrome) and have seen some intermittent problems that were caused temporary devops availability issues. Unfortunately any availability issues caused by the Bluemix/devops infrastructure or services (e.g. because of upgrades or scheduled maintenance) are out of our control and cannot be addressed by the Simple Data Pipe application.

**Closed by ptitzler** 2015-10-23 00:01 UTC
